# Generated by Django 5.2.5 on 2025-10-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('rol_id', models.IntegerField()),
                ('password', models.CharField(db_column='contraseña_hash', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
